### ISSUE TITLE
使用的旧代码？？需要操作ui？

### ISSUE THREAD

**Issue by xfunforx** [veryyoung/QQLuckyMoney#1]
从哪找的旧代码吗？最原始的才需要操作ui，后面的实现都不需要操作ui的。
somecode就是不需要ui操作的。可以参考下。

**Comment by veryyoung** [comment]
@xfunforx  之前的版本都是通过 activity 跳转来实现自动抢红包的，现在不需要了。

多谢你之前的 somecode

**Comment by veryyoung** [comment]
@xfunforx 有人说我直接把你的代码搬去上架了呢。感觉还是有不同的地方的是吧？ 哈哈

**Comment by xfunforx** [comment]
哈哈。。本来就是开源的。只不过你github上的代码是旧的代码而已。
你弄成app也是好事啊。只要不卖（捐赠除外）给那些不明真相的群众就好。
