### ISSUE TITLE
求加入“禁言不抢”的选项

### ISSUE THREAD

**Issue by foxdodo** [veryyoung/QQLuckyMoney#16]
群里禁言然后发口令红包，插件还是会自动抢，很容易就暴露了

**Comment by yulonh** [comment]
微信6.3.27用不了了，完全hook不了。

**Comment by 18641576720** [comment]
刚安装的时候 是好使，  但是过了30分钟左右 不好使了  ， 手机从新做系统 再装也是一样， 过不长时间就不好使了 可以手动收红包  软件不好使，  1.0.6  1.0.7 这2个版本
