### ISSUE TITLE
6.5.8无法抢哦

### ISSUE THREAD

**Issue by yyxida** [veryyoung/QQLuckyMoney#19]
更新了最新的正式版qq和插件，插件无法运行，

**Comment by veryyoung** [comment]
@yyxida 亲测可行

**Comment by yyxida** [comment]
索尼xperia z3，框架版本v86，无法使用，图片已发送到了你邮箱，麻烦看看，谢谢。

**Comment by AskQi** [comment]
华为荣耀7 EMUI4.0(安卓6.0) xp版本 v86
也不能用

**Comment by ps0660** [comment]
微信冲突，闪退

**Comment by veryyoung** [comment]
@ps0660 参考 https://github.com/veryyoung/WechatLuckyMoney/issues/13
