### ISSUE TITLE
1.0.3版本延时抢功能失效

### ISSUE THREAD

**Issue by lin375691011** [veryyoung/QQLuckyMoney#2]
1.0.3版本 设置延时抢之后没有效果  还是立刻抢，不知是我设置的问题还是有Bug。。请检查一下  麻烦了

**Comment by veryyoung** [comment]
装完插件需要重启。

**Comment by lin375691011** [comment]
我安装完成了，重启过了，抢的功能没问题，延时功能不能用。比如说我设置6秒之后再抢，可插件还是立刻抢。。

**Comment by ylmm** [comment]
这个延时我也不能使用，请作者辛苦一下，检查下代码。适当延时是防封策略之一，迫切需要！求更新！
