### ISSUE TITLE
6.5.8插件无法运行

### ISSUE THREAD

**Issue by 3215** [veryyoung/QQLuckyMoney#22]
更新qq6.5.8后，插件就无法正常运行了。
请修复一下

**Comment by ayong219** [comment]
别人应该给你修复么，说的那么理所当然。

2016-10-31 0:05 GMT+08:00, 3215 <notifications@github.com>:
> 更新qq6.5.8后，插件就无法正常运行了。
> 请修复一下
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/veryyoung/QQLuckyMoney/issues/22


-- 
我是杰克鲍尔

**Comment by ps0660** [comment]
QQ658抢红包，对微信有冲突，闪退

**Comment by veryyoung** [comment]
@ps0660 参考 https://github.com/veryyoung/WechatLuckyMoney/issues/13

**Comment by itlijiang** [comment]
我的是之前会使微信卡顿，现在微信更新了，不卡微信了，昨晚还能抢，今天早上又不可以了，蓝瘦，香菇啊。麻烦作者更新一下哈
