### ISSUE TITLE
Title can

### ISSUE THREAD

**Issue by xhsJ88** [veryyoung/QQLuckyMoney#26]
Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies 
of this license document, but changing it is not allowed.

**Comment by xhsJ88** [comment]
怎么不能抢啊

**Comment by xhsJ88** [comment]
怎么关闭啊

**Comment by veryyoung** [comment]
麻烦您别在这灌水了行吗？每天有这种无意义的通知真烦人。 @xhsJ88
