### ISSUE TITLE
红包金额如何记录？

### ISSUE THREAD

**Issue by MyMSDY** [veryyoung/QQLuckyMoney#34]
你好，
抢到的红包我想记录其金额。
Object o = callMethod(pickObject, "a", hongbaoRequestUrl.toString());
这个o是一个Bundle，里面的data字段是hongbaoRequestUrl网址返回的数据，
金额是不是在这个加密的数据里，需要如何解密或者记录抢到的金额？
可以单独联系我QQ990332019

**Comment by veryyoung** [comment]
@MyMSDY 没必要查金额啊。红包记录里面找去。

**Comment by MyMSDY** [comment]
我知道手动点开红包记录那里可以看到自己抢的金额，
但我需要实时记录传递给我自己的程序。

**Comment by veryyoung** [comment]
@MyMSDY  Bundle 都得到了，剩下的就很简单了，自己摸索吧。

友情提醒，我这个开源代码使用了 GPL 协议，如果想把 apk 分发给被人，麻烦把程序开源。谢谢

**Comment by MyMSDY** [comment]
@veryyoung 
我只是想更完善这个功能，也只是在你的这代码上修改了，逆向这块我不会。
目前我添加了口令红包关键字屏蔽，
![da295c2678492d2b8c318769c93b3534](https://cloud.githubusercontent.com/assets/24983102/21747023/39c8dd64-d594-11e6-96fc-476b41cf6221.jpg)
有人说记录今天抢到的金额就更好了，所以前来问你。
这程序我也并没有拿来盈利。

**Comment by veryyoung** [comment]
@MyMSDY 不管盈利与否，你分发给任何一个人用，你就需要开源，这是 GPL 协议的要求。

所以你还是开源出来吧，要么就放弃。

**Comment by jlhuang1224** [comment]
@veryyoung 开源协议是直接在readme.md声明的吗？

**Comment by veryyoung** [comment]
加个 licence 文件就行了，参考 https://github.com/veryyoung/QQLuckyMoney/blob/master/LICENSE
