### ISSUE TITLE
关于实现不用再跟随QQ更新而更新

### ISSUE THREAD

**Issue by aiuuyoyo** [veryyoung/QQLuckyMoney#37]
每次QQ更新之后，红包软件都会随之更新！记得fkzhang好像实现过不随QQ版本更新而更新红包软件。希望你也能实现。关于实现想法：如果已知类名，通过返回值类型和传入参数类型找到想要的方法，进而获取方法名！当然这样会一定程度上拖慢速度，可以考虑将上述实现方法只在发现新版本QQ之后初始化一次，将获取的数据保存在本地。谢谢

**Comment by veryyoung** [comment]
@aiuuyoyo 这个在考虑中，但是没空搞。
