### ISSUE TITLE
口令红包增加禁言开关

### ISSUE THREAD

**Issue by vito16** [veryyoung/QQLuckyMoney#41]
新增在QQ群禁言状态下是否继续抢红包的开关以及功能实现

**Comment by lintuhua** [comment]
你好，你能研究一下怎样获取是谁的红包吗？我刚把金额提示弄好，如果能提示到是谁的红包就更好了

**Comment by veryyoung** [comment]
@lintuhua 最后一段代码得到的是一个 bundle，从 bundle 中能得到一些信息，我猜的啊，哈哈。
