### ISSUE TITLE
Xposed日志报错InvocationTargetError

### ISSUE THREAD

**Issue by xxmali** [veryyoung/QQLuckyMoney#42]
QQ: v6.6.8
QQLuckyMoney: v1.1.0
Xposed: v87

01-21 10:10:40.196 E/Xposed  ( 8713): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.UnsatisfiedLinkError: Shared library "/data/data/com.tencent.mobileqq/app_lib/qwallet_plugin/libcftutils_v1.2.3.so" already opened by ClassLoader 0x12ca7820; can't open in ClassLoader 0x1454a200
01-21 10:10:40.196 E/Xposed  ( 8713): 	at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1270)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at me.veryyoung.qq.luckymoney.Main$1.afterHookedMethod(Unknown Source)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.data.MessageForQQWalletMsg.doParse(<Xposed>)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.data.ChatMessage.parse(ProGuard:64)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.message.BaseMessageManager.a(ProGuard:1198)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:1750)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:960)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.message.QQMessageFacade.a(ProGuard:790)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(ProGuard:860)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(ProGuard:109)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.MessageHandler.h(ProGuard:2422)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.MessageHandler.a(ProGuard:3875)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.service.MobileQQServiceBase.a(ProGuard:309)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.service.MobileQQService.a(ProGuard:663)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.app.QQAppInterface.a(ProGuard:9094)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.compatible.TempServlet.onReceive(ProGuard:52)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at mqq.app.MSFServlet.onReceive(MSFServlet.java:39)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at mqq.app.ServletContainer.notifyMSFServlet(ServletContainer.java:125)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at mqq.app.MainService.receiveMessageFromMSF(MainService.java:261)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at mqq.app.MainService.access$300(MainService.java:67)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at mqq.app.MainService$5.onRecvCmdPush(MainService.java:830)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(MsfRespHandleUtil.java:186)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at mqq.app.MainService$2.run(MainService.java:459)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at java.lang.Thread.run(Thread.java:818)
01-21 10:10:40.196 E/Xposed  ( 8713): Caused by: java.lang.UnsatisfiedLinkError: Shared library "/data/data/com.tencent.mobileqq/app_lib/qwallet_plugin/libcftutils_v1.2.3.so" already opened by ClassLoader 0x12ca7820; can't open in ClassLoader 0x1454a200
01-21 10:10:40.196 E/Xposed  ( 8713): 	at java.lang.Runtime.load(Runtime.java:331)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at java.lang.System.load(System.java:981)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at tencent.com.cftutils.EncUtilBase.loadSoByPath(Unknown Source)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at tencent.com.cftutils.EncUtilBase.<init>(Unknown Source)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at tencent.com.cftutils.DesEncUtil.<init>(Unknown Source)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at com.tenpay.android.qqplugin.a.q.a(Unknown Source)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at java.lang.reflect.Method.invoke(Native Method)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-21 10:10:40.196 E/Xposed  ( 8713): 	at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1262)
01-21 10:10:40.196 E/Xposed  ( 8713): 	... 24 more

**Comment by veryyoung** [comment]
这个我也遇到过，重启一次之后就好了

**Comment by xxmali** [comment]
Miui 7.1.12/7.1.20 Xposed v87 by SolarWarez
重启了5次未果，都是如此，有红包时报错。脸黑😥

**Comment by Z4HD** [comment]
据说这个跟QQ版本也有一定关系。
你还能报出错来不错了，这个插件在我的手机（Moto X Style XT1570，5.1.1，V87）上对所有6.x的QQ版本不起任何作用，日志里也没有相关的内容，其他的Xposed插件都正常。我只能眼睁睁的看着红包发出来，无论是框架日志还是我的QQ都静悄悄的。看来这个框架的有效性还得看脸。

**Comment by 1265578519** [comment]
这个插件对MIUI支持不好  多重启 只能说  成功了别关机
