### ISSUE TITLE
很想知道原理

### ISSUE THREAD

**Issue by fly7632785** [veryyoung/QQLuckyMoney#45]
你好，发现，这个hook的深度好厉害，很想知道，作者是怎么一步一步发觉这些hook点，又是如何逆向得如此彻底？

哦还有，6.6.9最新版本，我看到代码里面说支持，但是，我试了一下，好像不行呢。
这是加速抢红包，还是自动抢红包呀？

**Comment by Z4HD** [comment]
功能上是全自动抢红包，不过能不能用还得看运气。目前估计可以满足作者他的自用需求。

**Comment by veryyoung** [comment]
@Z4HD 是能用的，不能用自己找找原因吧。

**Comment by fly7632785** [comment]
哦   拉下来 不能用  会不会因为 我没有签名打包
