### ISSUE TITLE
小米note顶配不起作用，错误日志贴上，希望改进！谢谢

### ISSUE THREAD

**Issue by chulinx** [veryyoung/QQLuckyMoney#46]
01-22 20:05:30.458 E/Xposed  (27237): java.lang.ClassCastException: de.robv.android.xposed.installer.util.InstallZipUtil$XposedProp cannot be cast to java.util.Map

**Comment by Z4HD** [comment]
建议贴错误报告的时候附上一些相关点的信息比如所使用的QQ版本，Android版本，框架版本等。一上来就写个小米Note顶配感觉像是来炫手机的。

作者本人曾表示该框架经其测试无任何缺陷，发生问题建议先从自身找原因。

**Comment by veryyoung** [comment]
@chulinx 你贴的日志和我的框架毫无关系。
