### ISSUE TITLE
华为4X移动，QQ版本6.6.0，不抢红包咋回事？

### ISSUE THREAD

**Issue by sgfeeling** [veryyoung/QQLuckyMoney#49]

**Comment by Z4HD** [comment]
自己找原因

**Comment by sgfeeling** [comment]
我也想自己解决，可本人门外汉一个，你们编的代码我也看不懂，只能请教你们几个大神了！麻烦给指点指点！在用的手机为华为4X移动版Android5.0.2,Xposed installer 3.1.1,框架版本87。

**Comment by Z4HD** [comment]
有些时候这个框架抢到红包不会有任何提示，也不会弹出红包界面，建议您去QQ钱包的“交易记录”中查询是否抢到。

**Comment by sgfeeling** [comment]
QQ版本一个一个的试，试到6.6.6的版本能用了，非常感谢！
