### ISSUE TITLE
支持 MIUI 多开

### ISSUE THREAD

**Issue by sanxiaozhizi** [veryyoung/QQLuckyMoney#51]
希望支持MIUI的应用双开的QQ（目前最新版本会提示没抢到）
另外希望在QQ应用中加一个设置入口（像fkzhang的一样），这样就可以分别设置QQ和双开QQ的配置
另，建议加入 抢红包记录。

如果当前QQ版本不兼容，希望进入QQ的时候弹个toast提示一下（程序里有检查更新就更好了 ）

**Comment by sanxiaozhizi** [comment]
Here are some suggests.

**Comment by 1265578519** [comment]
miui8一直用不了

**Comment by Z4HD** [comment]
安装Xposed框架了吗？

**Comment by sanxiaozhizi** [comment]
@Z4HD Sure。普通QQ有效，双开的无效

**Comment by 1265578519** [comment]
肯定装了啊 希望插件载入成功来个提示吧 把设置接口放进去QQ设置里面？

**Comment by sinntd** [comment]
为什么miui8用不了的…

**Comment by veryyoung** [comment]
@sanxiaozhizi 双开的 package 是什么？

**Comment by sanxiaozhizi** [comment]
@veryyoung  MIUI自带的系统功能，貌似没有package名称吧

**Comment by veryyoung** [comment]
@sanxiaozhizi 如果 package 没区别，那应该就能用。

**Comment by sanxiaozhizi** [comment]
@veryyoung 的确不行呀，全部的红包类型都试过了，都不行fkzhang的那个可行，你可以参考参考那个
