### ISSUE TITLE
miui8 1.1.2打开APP闪退停止响应

### ISSUE THREAD

**Issue by 1265578519** [veryyoung/QQLuckyMoney#57]
miui8 1.1.2打开APP闪退停止响应，具体原因不知道 1.1.1没问题

**Comment by sgfeeling** [comment]
我的华为4X，EMUI3.1，跟楼上一样打开1.1.2就闪退停止响应

**Comment by lvsj575** [comment]
同样，flyme4.2.1打开闪退

**Comment by Anklerwa** [comment]
flyme6.0 闪退

**Comment by veryyoung** [comment]
卸载重装就好了。以前的配置现在换类型了。

**Comment by zhukai1204** [comment]
vivo 好像不能用

**Comment by sinntd** [comment]
卸载重装或者清除数据就好了。以前的配置现在换数据类型，导致转换出错。

都试过了，miui8的用户 qq版本是6.6.9，完全抢不到orz

**Comment by sinntd** [comment]
卸载重装或者清除数据就好了。以前的配置现在换数据类型，导致转换出错。

都试过了，miui8的用户 qq版本是6.6.9没有使用双开，完全抢不到orz
