### ISSUE TITLE
为什么我升级开了，抢不了红包了啊？？

### ISSUE THREAD

**Issue by nougat7** [veryyoung/QQLuckyMoney#59]

**Comment by 1265578519** [comment]
多重启几次手机，有几率能用的，估计是兼入点没做好，能做到和QQ防撤回那个一样在QQ设置中加入选项应该就可以不出问题了

**Comment by caizhenbin** [comment]
更新完直接显示出错停止运行了

**Comment by veryyoung** [comment]
@caizhenbin  https://github.com/veryyoung/QQLuckyMoney/issues/57
